/**
 * 디자인 패키지의 `I.X` API 를 lucide-react 로 백킹.
 * 디자인 icons.jsx 의 export 표면 그대로 유지 — 컴포넌트 jsx → tsx 변환을 메커니컬하게.
 */
import {
  Search,
  Plus,
  Copy,
  Check,
  ChevronRight,
  ChevronDown,
  X,
  Filter,
  Calendar,
  Settings,
  Home,
  List,
  Layers,
  Clock,
  BookOpen,
  Trash2,
  Edit3,
  Send,
  Archive,
  Sparkles,
  ArrowUp,
  ArrowDown,
  Command,
  Tag,
  MapPin,
  MoreHorizontal,
  Pin,
  RefreshCw,
  Eye,
  Inbox,
  Zap,
  FileText,
  Loader2,
  HelpCircle,
  CornerDownLeft,
  LayoutDashboard,
  Webhook,
  Activity,
  Power,
  ExternalLink,
  Link2,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

// Design 의 `I.X` 가 `<I.X size={13}/>` 형태로 호출됨.
// lucide-react 도 동일하게 size prop 지원.
export const I = {
  Search,
  Plus,
  Copy,
  Check,
  Chevron: ChevronRight,
  ChevDown: ChevronDown,
  X,
  Filter,
  Calendar,
  Settings,
  Home,
  List,
  Layers,
  Clock,
  Book: BookOpen,
  Trash: Trash2,
  Edit: Edit3,
  Send,
  Archive,
  Sparkle: Sparkles,
  ArrowUp,
  ArrowDown,
  Cmd: Command,
  Tag,
  MapPin,
  More: MoreHorizontal,
  Pin,
  Refresh: RefreshCw,
  Eye,
  Inbox,
  Zap,
  FileText,
  Loader: Loader2,
  Help: HelpCircle,
  CornerDownLeft,
  Layout: LayoutDashboard,
  Webhook,
  Activity,
  Power,
  External: ExternalLink,
  Link: Link2,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof I;
export type { LucideProps };
// 별칭 (이전 코드 호환)
export const Icon = I;
